version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
      - automated
      - github_actions
    # only update HashiCorp actions, external actions managed by TSCCR
    groups:
      github-actions-breaking:
        update-types:
          - major
      github-actions-backward-compatible:
        update-types:
          - minor
          - patch
  
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
