name: hil
on:
  push:

permissions:
  contents: read
            
jobs:
  linux-tests:
    runs-on: ubuntu-latest
    env:
      TEST_RESULTS_PATH: "/tmp/test-results"
    strategy:
      matrix:
        go-version:
          - '1.14'
          - 'oldstable'
          - 'stable'
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Make Test Directory
        run: mkdir -p "$TEST_RESULTS_PATH"/hil
      
      - name: Setup Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install gotestsum
        uses: autero1/action-gotestsum@7263b9d73912eec65f46337689e59fac865c425f # v2.0.0
        with:
          gotestsum_version: 1.9.0

      - name: Run gotestsum
        env:
          PLATFORM: linux
          REPORT_FILE: ${{ env.TEST_RESULTS_PATH }}/hil/gotestsum-report.xml
        run: |-
          gotestsum --format=short-verbose --junitfile ${{ env.REPORT_FILE }} -- -p 2 ./...

      - name: Upload Test Results
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          path: ${{ env.TEST_RESULTS_PATH }}
          name: tests-linux
  
  windows-tests:
    runs-on: windows-latest
    env:
      TEST_RESULTS_PATH: 'c:\Users\runneradmin\AppData\Local\Temp\test-results'
    strategy:
      matrix:
        go-version:
          - '1.14'
          - 'oldstable'
          - 'stable'
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Setup Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install gotestsum
        uses: autero1/action-gotestsum@7263b9d73912eec65f46337689e59fac865c425f # v2.0.0
        with:
          gotestsum_version: 1.9.0

      - name: Run gotestsum
        env:
          PLATFORM: windows
          REPORT_FILE: ${{ env.TEST_RESULTS_PATH }}/hil/gotestsum-report.xml
        run: |-
          gotestsum.exe --format=short-verbose --junitfile ${{ env.REPORT_FILE }} -- -p 2 ./...

      - name: Upload Test Results
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          path: ${{ env.TEST_RESULTS_PATH }}
