name: hil
on:
  push:

permissions:
  contents: read
            
jobs:
  linux-tests:
    runs-on: ubuntu-latest
    env:
      TEST_RESULTS_PATH: "/tmp/test-results"
    strategy:
      matrix:
        go-version:
          - '1.14'
          - 'oldstable'
          - 'stable'
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Make Test Directory
        run: mkdir -p "$TEST_RESULTS_PATH"/hil
      
      - name: Setup Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install gotestsum
        uses: autero1/action-gotestsum@7263b9d73912eec65f46337689e59fac865c425f # v2.0.0
        with:
          gotestsum_version: 1.9.0

      - name: Run gotestsum
        env:
          PLATFORM: linux
          REPORT_FILE: ${{ env.TEST_RESULTS_PATH }}/hil/gotestsum-report.xml
        run: |-
          gotestsum --format=short-verbose --junitfile ${{ env.REPORT_FILE }} -- -p 2 ./...

      - name: Upload Test Results
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          path: ${{ env.TEST_RESULTS_PATH }}
          name: tests-linux
  
  windows-tests:
    runs-on: windows-latest
    env:
      TEST_RESULTS_PATH: 'c:\Users\runneradmin\AppData\Local\Temp\test-results'
    strategy:
      matrix:
        go-version:
          - '1.14'
          - 'oldstable'
          - 'stable'
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install gotestsum
        uses: autero1/action-gotestsum@7263b9d73912eec65f46337689e59fac865c425f # v2.0.0
        with:
          gotestsum_version: 1.9.0

      - name: Run gotestsum
        env:
          PLATFORM: windows
          REPORT_FILE: ${{ env.TEST_RESULTS_PATH }}/hil/gotestsum-report.xml
        run: |-
          gotestsum.exe --format=short-verbose --junitfile ${{ env.REPORT_FILE }} -- -p 2 ./...

      - name: Upload Test Results
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          path: ${{ env.TEST_RESULTS_PATH }}
